# Generated by Django 3.0 on 2023-09-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeWoods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='prdct_id',
            field=models.PositiveIntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
