# Generated by Django 3.0 on 2023-09-17 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeWoods', '0002_auto_20230916_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=35)),
                ('c_number', models.CharField(max_length=12)),
                ('c_expdate', models.CharField(max_length=5)),
                ('c_cvv', models.CharField(max_length=3)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
