# Generated by Django 3.0 on 2023-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeWoods', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='s_stat',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
